### ISSUE TITLE
why isn't WLED+ open-source?

### ISSUE THREAD

**Issue by wojgie** [pixel-heart/wledplus-releases#1]
Just a question

**Comment by tokudu** [comment]
Thanks for asking. There are two main reasons: 
1) The app is built on a common framework that I'm sharing for between multiple apps that I'm working on, so making it open source would require open sourcing the framework, which is a bit more effort. 
2) It's still very early and I'm not yet sure what future the app holds. If it gets enough traction with the community and and there is a lot of interest in contributing, i'd be more incentivized to open source it. 
I hope that make sense
